# Generated by Django 3.2.9 on 2022-05-30 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('title', models.CharField(help_text='제목 입니다.', max_length=32, verbose_name='제목')),
                ('article', models.TextField(help_text='내용 입니다.', verbose_name='내용')),
                ('music_code', models.CharField(help_text='악보 코드 입니다.', max_length=32, verbose_name='악보 코드')),
            ],
            options={
                'verbose_name': '게시글',
                'db_table': 'post_tb',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('image', models.ImageField(help_text='게시글 이미지 입니다.', upload_to='post/image/%Y/%m/%d', verbose_name='게시글 이미지')),
                ('post', models.ForeignKey(blank=True, help_text='게시글 입니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postimage_posts', to='community.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 이미지',
                'db_table': 'post_image_tb',
            },
        ),
    ]
