# Generated by Django 3.2.9 on 2022-05-30 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(help_text='작성자 입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='post_writers', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
